### ISSUE TITLE
Create a new testing repo in Github

### ISSUE THREAD

**Issue by martinrobled0** [WizelineLabs/project-lab#294]
Follow the steps:

1. Log into the GitHub
2. Move to the GitHub Repositories page
3. Click on the green “New” button
4. This will bring up the GitHub repo creation wizard
5. Select 'Wizeline' as Owner
6. Enter the name of the [GitHub repository]
7. Include a description
8. Choose to make this a public or [private GitHub repository]
9. Add a README (optional)
10. Include a .gitignore file for your development framework (optional)
11. Choose a fair use license
12. Click the green “Create Repository” button to finish the process

**Comment by pfaversa** [comment]
**Advantages of Cypress**

- Tests run inside a real browser, which give us results that are almost identical to what  users are going to experience.
- Mock API Request. It also has access to the network layer over application which allows  us to control all the network requests. 
- Cypress has access to all the browser’s resources
- Take screenshots
- Record a video
- Using Cypress, QAs or developers can create: Unit tests, Integration tests, End to End tests
- Simon.js (Test Doubles in Unit Testing)

**Limitation of Cypress**
- It doesn’t provide support for multi-tabs.
- Cannot test drive browsers at the same time.
- Limited support for iFrames.
- Cypress only supports Javascript (Selenium provides the flexibility to select the programming language of their choice like Java, Python)
- Cypress has experimental support for WebKit (Safari).
- Cypress will never be able to run on a native mobile app but you can control the viewport with the cy.viewport() command to test responsive, mobile views in a website or web application. You can also mimic certain behaviors like swiping

**Comment by pfaversa** [comment]
Step 1: clon repo “cypress-project-lab”
Step 2: npm init -y
Step 3: npm install cypress --save-dev
Step 4: npm install prettier --save-dev
Step 5: npm install typescript --save-dev
Step 6: npx tsc --init

**Comment by pfaversa** [comment]
Finally, the team decided to keep the e2e tests in the same dev repo
