### ISSUE TITLE
Implement a "hot" sorting algorithm like in reddit or hacker news

### ISSUE THREAD

**Issue by jackbravo** [WizelineLabs/project-lab#31]
[This](https://stackoverflow.com/questions/34143895/how-to-recreate-reddit-sorting-in-django-queryset) StackOverflow question offers a good summary of what is needed to do:

> reddit stores sort values for links (and comments) in a cache of sorts; the vote processor then calculate the new sort value and stores that. This ends up being a lot easier than trying to do on-the-fly sort calculations in the query, like you're doing. It's also generally more efficient, since you'll only have one calculation for each vote, whereas your approach will recalculate every post's sort value on each read.

And has a [link](https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.pyx#L44-L58) to python code to how reddit used to do it in the past.

This [medium article](https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9) also offers a more detailed explanation.

It can also be implemented in SQL, [this](http://restfulmvc.com/reddit-algorithm.shtml) is an example, but the actual result should be cached, maybe by doing an UPDATE query that runs in the background.

**Comment by martinrobled0** [comment]
With this, We still need the sort input of the main page? 🤔
